# Environment configuration
# =========================

env_default: &env_default
  working_directory: ~/near-membrane
  docker:
    - image: circleci/node:14-browsers


# Commands definitions
# ====================

# Yarn cache
restore_yarn_cache: &restore_yarn_cache
  restore_cache:
    keys:
      - yarn-v4-{{ checksum "yarn.lock" }}

save_yarn_cache: &save_yarn_cache
  save_cache:
    key: yarn-v4-{{ checksum "yarn.lock" }}
    paths:
      - ~/.cache/yarn

# Workspace
save_workspace: &save_workspace
  persist_to_workspace:
    root: .
    paths: .

load_workspace: &load_workspace
  attach_workspace:
    at: ~/tmp/workspace

# Build
install: &install
  run:
    name: Install and build
    command: |
      yarn install --frozen-lockfile
      yarn build

# Checks
run_linting: &run_linting
  run:
    name: Run linting
    command: yarn lint

# Jest tests for near-membrane-node
run_node_tests: &run_node_tests
  run:
    name: Run Node tests (Jest)
    command: yarn coverage:jest

# Karma tests for near-membrane-dom
run_browser_tests: &run_browser_tests
  run:
    name: Run DOM tests (Karma)
    command: yarn coverage:karma

# Merge the two coverage reports
merge_coverage: &merge_coverage
  run:
    name: Merge Coverage Reports
    command: |
      yarn coverage:merge
      yarn coverage:report

store_coverage: &store_coverage
  store_artifacts:
    path: coverage-merged


# Jobs definition
# ===============

version: 2
jobs:
  build:
    <<: *env_default
    steps:
      - checkout

      - *restore_yarn_cache
      - *install
      - *save_yarn_cache
      - *save_workspace

      - *run_linting
      - *run_node_tests
      - *run_browser_tests

      - *merge_coverage
      - *store_coverage


# Workflows definition
# ====================

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
